app = 'crowdcrawl'
primary_region = 'arn'

[build]

[env]
  PORT = "8083"
  ERL_AFLAGS = "-kernel inet_dist_use_interface {0,0,0,0,0,0,0,0} -proto_dist inet6_tcp"

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
